### ISSUE TITLE
Illegal Argument Exception thrown when connecting rds postgress 10 with kinesis.

### ISSUE THREAD

**Issue by anshu2212** [disneystreaming/pg2k4j#14]
I installed your application using docker. connected the rds and kinesis but container stops with error
    `ERROR com.disneystreaming.pg2k4j.SlotReaderKinesisWriter - Received exception of type class 
    java.lang.IllegalArgumentException
    java.lang.IllegalArgumentException: Data must be less than or equal to 1MB in size, got 9909154 bytes
        	at 
  com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:517)
	       at 
  com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:406)
	      at 
 com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.lambda$processByteBuffer$0(SlotReaderKinesisWriter.java:242)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at 
 com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.processByteBuffer(SlotReaderKinesisWriter.java:234)
	at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.readSlotWriteToKinesisHelper(SlotReaderKinesisWriter.java:195)
	at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.readSlotWriteToKinesis(SlotReaderKinesisWriter.java:131)
	at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.runLoop(SlotReaderKinesisWriter.java:86)
	at com.disneystreaming.pg2k4j.CommandLineRunner.run(CommandLineRunner.java:30)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.disneystreaming.pg2k4j.CommandLineRunner.main(CommandLineRunner.java:45)
`

I know there is a limit of 1 MB data to be sent to the kinesis.

But I have set 'max_wal_size' to 1024.

**Comment by rkass** [comment]
It seems like the issue here is that you're receiving chunks from the WAL that are larger than 1MB, and when pg2k4j tries to put this to Kinesis, the KPL complains that the record is larger than 1MB. You mentioned that you have your 'max_wal_size' set to 1024, but I don't think this is the configuration value you want to toggle. Instead, have a look at the [wal_writer_flush_after](https://www.postgresql.org/docs/10/runtime-config-wal.html#GUC-WAL-WRITER-FLUSH-AFTER) and [wal_writer_delay](https://www.postgresql.org/docs/10/runtime-config-wal.html#GUC-WAL-WRITER-DELAY) configurations.

If you turn down wal_writer_flush_after to, say, 500KB then I expect this will solve your problem. This will cause changes to the WAL to come in smaller more frequent batches to the replication slot.

**Comment by rkass** [comment]
Closing issue. @anshu2212 Please reopen if the above doesn't work for you.

**Comment by a-ninja** [comment]
@anshu2212 Did setting wal_writer_flush_after to a lower value solve the problem?

**Comment by jiricuypers** [comment]
I have tried the above, but unfortunately this doesn't work for me.   I have used DBeaver's duplicate table feature and it only works when specifying really small values for "process per x" items at a time.  Any other suggestions?
