### ISSUE TITLE
On startup a replication slot was created but is being used by another process.

### ISSUE THREAD

**Issue by jamesamurr-bind** [disneystreaming/pg2k4j#35]
On an rds postgres instance that did not have replication enabled before using pg2k4j I enabled replication and ran the pg2k4j cli to connect to it. I verified that no pg2k4j replication slot existed before running the cli. The cli connects but errors out with the error shown below. It appears to have created the replication slot, but some other process has decided to connect to it, so now pg2k4j can't connect to it. Any ideas??

I'm running on the disneystreaming/pg2k4j docker image that I pulled yesterday (10/7/2019)
Running against postgres version 10.6

```
[main] INFO com.disneystreaming.pg2k4j.PostgresConnector - Attempting to create replication slot pg2k4j
[main] INFO com.disneystreaming.pg2k4j.PostgresConnector - Slot pg2k4j already exists
[main] INFO com.disneystreaming.pg2k4j.PostgresConnector - Replication slot currently has another process consuming from it
[main] INFO com.disneystreaming.pg2k4j.PostgresConnector - Sleeping for 30 seconds before retrying 29 more times
org.postgresql.util.PSQLException: ERROR: replication slot "pg2k4j" is active for PID 7957
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
        at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1116)
        at org.postgresql.core.v3.QueryExecutorImpl.startCopy(QueryExecutorImpl.java:842)
        at org.postgresql.core.v3.replication.V3ReplicationProtocol.initializeReplication(V3ReplicationProtocol.java:58)
        at org.postgresql.core.v3.replication.V3ReplicationProtocol.startLogical(V3ReplicationProtocol.java:42)
        at org.postgresql.replication.fluent.ReplicationStreamBuilder$1.start(ReplicationStreamBuilder.java:38)
        at org.postgresql.replication.fluent.logical.LogicalStreamBuilder.start(LogicalStreamBuilder.java:37)
        at com.disneystreaming.pg2k4j.PostgresConnector.getPgReplicationStreamHelper(PostgresConnector.java:228)
        at com.disneystreaming.pg2k4j.PostgresConnector.getPgReplicationStream(PostgresConnector.java:184)
        at com.disneystreaming.pg2k4j.PostgresConnector.<init>(PostgresConnector.java:98)
        at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.createPostgresConnector(SlotReaderKinesisWriter.java:293)
        at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.readSlotWriteToKinesis(SlotReaderKinesisWriter.java:123)
        at com.disneystreaming.pg2k4j.SlotReaderKinesisWriter.runLoop(SlotReaderKinesisWriter.java:86)
        at com.disneystreaming.pg2k4j.CommandLineRunner.run(CommandLineRunner.java:30)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at com.disneystreaming.pg2k4j.CommandLineRunner.main(CommandLineRunner.java:45)
```

**Comment by jamesamurr-bind** [comment]
I'm closing this. The issue was that I had other docker containers running pg2k4j. I exited them unclean and they stuck around and were connecting before my current container could connect. I cleaned them up and now it works.
